name: Build and deploy to GH pages

on:
  push:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: |
          cargo install --locked trunk

      - name: Build application
        run: |
          trunk build --release --public-url slide-puzzle

      - name: List contents
        run: ls -la

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
