name: Build and deploy to GH pages

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update local Rust toolchain
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy rustfmt --toolchain nightly

      - name: Get toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Add WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Lint
        run: |
          cargo +nightly fmt -- --check
          cargo +nightly clippy -- --no-deps -D warnings

      - name: Install trunk
        run: |
          cargo install --locked trunk

      - name: Build application
        run: |
          trunk build --release --public-url slide-puzzle

      - name: Benchmark
        run: |
          cargo bench

      - name: List contents
        run: ls -la

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
